name: Copy traynard release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "版本号"
        required: true
        default: "v1.4.1"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Upload to GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ inputs.tag }}
        run: |
          set -e

          FILE="traynard-portable.zip"
          URL="https://github.com/tabris17/traynard/releases/download/${TAG}/${FILE}"

          curl -fL "$URL" -o "$FILE"

          if gh release view "$TAG" --repo "$GITHUB_REPOSITORY" >/dev/null 2>&1; then
            gh release upload "$TAG" "$FILE" \
              --repo "$GITHUB_REPOSITORY" \
              --clobber
          else
            gh release create "$TAG" "$FILE" \
              --repo "$GITHUB_REPOSITORY" \
              --title "$TAG" \
              --notes "Copied from tabris17/traynard"
          fi
